my:
  greetings: Updated message Hello microservice, this is from config server
  list:
    values: "apple,banana,graps,watermelon"
db:
  connection: test-connection-from-config-server
  host:  128.0.0.1
  port:  2000
